name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install system dependencies
      run: sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev

    - name: Install Poetry
      run: pip install poetry

    - name: Install Python dependencies
      run: poetry install --with=dev

    - name: Build application
      run: poetry run bash ./scripts/build.sh

    - name: Create and upload release
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/resilio_sync_tray
